apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicebus 
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://<sb name>/;SharedAccessKeyName=<key name>;SharedAccessKey=<access keys>" 
  - name: queueName
    value: downloads
