apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicebus 
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://sbuslevelup.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XVDTOCbduT79kqlADPI+eIsOk7Whqgj9VeLr0oWwyLk=" 
  - name: queueName
    value: downloads
